### ISSUE TITLE
exec_no_cursor raises on sqlite3 errors instead of returning Result.Error

### ISSUE THREAD

**Issue by leviroth** [c-cube/sqlite3_utils#1]
I have a gist where I try to insert the same primary key twice into a table: https://gist.github.com/leviroth/3ce45434124b94be47c0834b86e29337

I would expect that the second time around, I would get back `Error CONSTRAINT` from `Sqlite3_utils`. But instead it appears that the [Rc.t] is checked internally and raised as an exception.

This happens on both 0.3.1 and when pinned to 6759dce6.

**Comment by c-cube** [comment]
would you mind testing more thoroughly on the `wip-fix1` branch?

**Comment by leviroth** [comment]
Looks good on both the `exec` and `exec_no_cursor` examples that I have. Re "more thoroughly," is there anything specific you'd like to check?

**Comment by c-cube** [comment]
Nothing springs to mind, unless you feel like adding more tests that exercise the error handling. Otherwise feel free to close :)
